global:
  scrape_interval: 1s
  evaluation_interval: 15s
  external_labels:
    monitor: exporter-metrics


scrape_configs:
- job_name: development
  scrape_interval: 1s

  static_configs:
    # These endpoints are scraped via HTTP.
    - targets:
      - 'localhost:9090'
      - '10.0.2.15:9100'